const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCT = "GET_PRODUCT";
const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";
const SIGNIN = "SIGNIN";
const SIGNOUT = "SIGNOUT";
const ADD_ORDERS = "ADD_ORDERS";

export {
  GET_PRODUCTS,
  GET_PRODUCT,
  ADD_PRODUCT_TO_BASKET,
  REMOVE_PRODUCT_FROM_BASKET,
  SIGNIN,
  SIGNOUT,
  ADD_ORDERS,
};
